# -*- coding: utf-8 -*-
"""11_4_26_Test..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJZLSvtoKZ9R737qTlF-meU0uzrHy97U
"""

# 1. What is a loop in Python? Explain the difference between for loop and while loop. (2)
# A loop is used to repeat a block of code multiple times until a condition is satisfied.
# Types of Loops:
# for loop
# Used when the number of iterations is known
# Iterates over a sequence list, string, range

# while loop
# Used when the number of iterations is not known
# Runs when the condition becomes False

#2. What is a nested loop? Give an example where nested loops are used in pattern printing. (2)
#A nested loop is a loop inside another loop. The inner loop runs completely every time then outer loop runs once.
for i in range(1, 5):
    for j in range(1, 5):
        print("*", end=" ")
    print()

#3. What is a string in Python? How is it different from other data types? (2)
# A string is a sequence of characters
# A string stores text characters , while other data types store numbers

#4. Explain the concept of immutability in strings. (2)
# Immutability means that once a string is created, it cannot be changed.
# You cannot modify individual characters of a string
# Any change creates a new string, not the current one
# Strings are immutable

#5. What is a palindrome? Explain with an example. (2)
#A palindrome is a word, number, or string that reads the same forward and backward.
s = "madam"
rev=""
i=len(s)-1
while i >= 0:
      rev = rev + s[i]
      i-=1
if s==rev:
  print("palindrome")
else:
  print("not palindrome")

#6. Write a program to print the following pattern: (5)
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(j,end=' ')
  print()

#7. Write a program to print the following pattern: (5)
n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
  print()

#8. Write a program to print a hollow square pattern: (5)
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i==1 or j==1 or i==n or j==n:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

#9. Write a program to print a palindromic number pyramid: (10)
n=5
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  for j in range(2,n+1):
    if i>=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()

#10. Write a program to print a butterfly pattern: (10)
n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

#11 Write a program to check whether a given string is a palindrome or not. (7.5)
s = "madam"
rev=""
i=len(s)-1
while i >= 0:
      rev = rev + s[i]
      i-=1
if s==rev:
  print("palindrome")
else:
  print("not palindrome")

#12. Write a program to reverse a string without using slicing ( [::-1] ). (7.5)
s = "python"
rev=""
i=len(s)-1
while i >= 0:
      rev = rev + s[i]
      i-=1
print(rev)

#13. Write a program to print all prime numbers between 2 and 100. (5)
for i in range(2, 101):
    count = 0
    for j in range(1, i+1):
        if i % j == 0:
            count += 1
    if count == 2:
        print(i)

s1='listen'
s2='silent'
isAnagram=True
if len(s1)==len(s2):
  for c in s1:
    if c not in s2:
      isAnagram=False
      break
else:
  isAnagram=False
if isAnagram:
  print('anagram')
else:
  print('not anagram')