# -*- coding: utf-8 -*-
"""1st pdf if.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5adaxNoWLHlWHPxxmJHNYJQPHuRskb2
"""

num=int(input("enter number="))
if(num >=  0):
  print("positive number")

num=int(input("enter number="))
if(num > 100):
  print("greater than 100")

num=int(input("enter number="))
if(num % 5 == 0):
  print("number is divisible by 5")

age=int(input("enter age="))
if(age >=  18):
  print("you're eligible for vote")

num=int(input("enter number="))
if(num % 2 == 0):
  print(num,"is even number")

num=int(input("enter number="))
if(num % 10 == 0):
  print(num,"is multiple of 10")

num=int(input("enter marks="))
if(num > 90):
  print("congartes")

num=int(input("enter temperature="))
if(num > 30):
  print("temperature is above")

slry=int(input("enter salary="))
if(slry > 50000):
  print("salary is more than 50k")

num=int(input("enter number="))
if(num <  0):
  print("number is less than 0")

num=int(input("enter number="))
if(num == 50):
  print("number is equal to 50")

marks=int(input("enter marks="))
if(marks >= 40):
  print("pass")

year=int(input("enter year="))
if(year > 2000):
  print("year is greater than 2000")

num=int(input("enter number="))
if(num % 3 == 0):
  print("num is divisible by 3")

speed=int(input("enter speed="))
if(speed > 80):
  print("speed is above 80")

wght=int(input("enter weight="))
if(wght > 70):
  print("weight is more than 70")

num=int(input("enter number="))
if(num >= 1 and num <= 10):
  print(num,"is between 1 and 10")

amount=int(input("enter amount="))
if(amount > 5000):
  print("your bonus is",amount)

score=int(input("enter score="))
if(score ==  0):
  print("yes score is equal to zero")

experience=int(input("enter experience="))
if(experience > 2):
  print("your exp. is more than 2 years")