# -*- coding: utf-8 -*-
"""1st pdf if else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1295j5w8V-tt4f5-VebKHHE4FRVzCUiFG
"""

num=int(input("enter number="))
if(num >= 0):
  print("positive")
else:
  print("negative")

num=int(input("enter number="))
if(num%2==0):
  print("even")
else:
  print("odd")

age=int(input("enter number="))
if(age >= 18):
  print("voting")
else:
  print("not voting")

num=int(input("enter number="))
if(num >= 50):
  print("num is greater than 50")
else:
  print("num is not greater than 50")

marks=int(input("enter number="))
if(marks >= 40):
  print("pass")
else:
  print("fail")

num=int(input("enter number="))
if(num%5== 0):
  print("divisible by 5")
else:
  print("not divisible by 5")

temp=int(input("enter number="))
if(temp > 30):
  print("temperature is hot")
else:
  print("temperature is normal")

sal=int(input("enter number="))
if(sal > 60000):
  print("salary is high")
else:
  print("salary is low")

num=int(input("enter number="))
if(num%7==0):
  print(num,"number is multiply by 7")
else:
  print(num,"number is not multiply by 7")

speed=int(input("enter number="))
if(speed > 80):
  print("speed is over limit")
else:
  print("speed limit is safe")

a=int(input("enter first number="))
b=int(input("enter second number="))
if(a > b):
  print("greater number is=",a)
elif(b > a):
  print("greater number is=",b)
else:
  print("number is equal")

num=int(input("enter number="))
if(num==0):
  print("number is zero")
else:
  print("number is non zero")

year=int(input("enter year="))
if((year%4==0 and year%100!=0) or year%400==0):
  print("leap year is",year)
else:
  print("not leap year is",year)

marks=int(input("enter marks="))
if(marks > 75):
  print("distinction")
else:
  print("normal")

num=int(input("enter number="))
if(num > 10):
  print("greater than 10")
elif(num < 10):
  print("less than 10")
else:
  print("equal to 10")

bonus=int(input("enter amount="))
if(bonus > 5000):
  print("bonus is given")
else:
  print("bonus is not given")

age=int(input("enter age="))
if(age < 18):
  print("minor")
else:
  print("adult")

num=int(input("enter number="))
if(num % 2==0):
  print(num,"number is divisible by 2")
elif(num % 3==0):
  print(num,"number is divisible by 3")
else:
  print("not divisible by both")

num=int(input("enter number="))
if(num > 100):
  print(num,"number is greater than 100")
elif(num == 100):
  print(num,"number is equal to 100")
else:
  print(num,"number is less than 100")

num=int(input("enter number="))
if(num > 85):
  print("eligible for scholarship")
else:
  print("not eligible for scholarship")

num=int(input("enter distance="))
if(num > 100):
  print("distance is long")
else:
  print("distance is short")

weight=int(input("enter weight="))
if(weight < 70):
  print("weight is normal")
else:
  print("weight is high")

score=int(input("enter score="))
if(score > 50):
  print("average")
else:
  print("below")

hours=int(input("enter hours="))
if(hours > 8):
  print("overtime")
else:
  print("normal")

num=int(input("enter number="))
if(num % 10==0):
  print(num,"number is divisible by 10")
else:
  print(num,"number is not divisible by 10")

num=int(input("enter amount="))
if(num > 0):
  print("profit is made")
else:
  print("loss")

age=int(input("enter age="))
if(age > 60):
  print("senior citizen")
else:
  print("not senior citizen")

num=int(input("enter number="))
if(num == 5**2):
  print(num,"is square of 5")
else:
  print(num,"is not square of 5")

num=int(input("enter number="))
if(num > 4):
  print("rating is good")
else:
  print("rating is average")

num=int(input("enter number="))
if(num > 20 and num > 30):
  print(num,"number is greater than both 20 and 30")
else:
  print(num,"number is not greater than both 20 and 30")