# -*- coding: utf-8 -*-
"""2d list_&_comprehension_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc7dS4XnWT2CbT0O1bDv0spCSHm7_1fE
"""

#1.Print a 2D list (matrix) row-wise.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
for i in range(len(li)):
  for j in range(len(li)):
    print(li[i][j],end=' ')
  print()

#2.Print a matrix column wise.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
for j in range(len(li)):
  for i in range(len(li)):
    print(li[i][j],end=' ')
  print()

#3. Find the sum of all elements in a matrix.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
sum=0
for i in range(len(li)):
  for j in range(len(li[i])):
    sum+=li[i][j]
print(sum)

#4. Find the largest element in a matrix.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
largest=0
for i in li:
  for j in i:
    if j > largest:
      largest = j
print(largest)

#5. Count total number of elements in a matrix.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
count=0
for i in li:
  for j in i:
    count+=1
print("total elements=",count)

#6. Transpose of a matrix.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
transposed_li=[]
for i in range(len(li)):
  row=[]
  for j in range(len(li[i])):
    row.append(li[j][i])
  transposed_li.append(row)
print(transposed_li)

#7. Add two matrices.
li_1 = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

li_2 = [[9, 8, 7],[6, 5, 4],[3, 2, 1]]
add=[]
for i in range(len(li_1)):
  row=[]
  for j in range(len(li_1[i])):
    row.append(li_1[i][j] + li_2[i][j])
  add.append(row)
print(add)

#8. Find the sum of each row only.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
for i in range(len(li)):
  row_sum=0
  for j in range(len(li[i])):
    row_sum+=li[i][j]
  print(row_sum)

#9. Find the maximum element in each row
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
for i in range(len(li)):
  max=0
  for j in range(len(li[i])):
    if li[i][j] > max:
      max=li[i][j]
  print(max)

#10. Count how many even and odd numbers are in the matrix.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
count_even=0
count_odd=0
for i in range(len(li)):
  for j in range(len(li[i])):
    if li[i][j] % 2 == 0:
      count_even+=1
    else:
      count_odd+=1
print("even count=",count_even)
print("odd count=",count_odd)

#11. Flatten a 2D list into a 1D list.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
flatten=[]
for i in range(len(li)):
  for j in range(len(li)):
    flatten.append(li[i][j])
print(flatten)

#12. Find the row with maximum sum.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
row=0
max_sum=0
for i in range(len(li)):
  current_sum=0
  for j in range(len(li[i])):
    current_sum+=li[i][j]
    if current_sum > max_sum:
      max_sum=current_sum
      row=i
print("max sum=",max_sum)
print("row index=",row)

#13. Replace all negative numbers in the matrix with 0.
li = [[1, -2, 3],[-4, 5,-6],[7, -8, 9]]
for i in range(len(li)):
  for j in range(len(li[i])):
    if li[i][j] < 0:
      li[i][j]=0
print(li)

#(Using List Comprehension)
#1. Create a list of squares from 1 to N.
li = [1, 2 , 3 , 4 , 5]
square=[i**2 for i in li]
print(square)

#2. Create a list of even numbers from a given list.
li = [1, 2 , 3 , 4 , 5]
even=[i for i in li if i % 2 == 0]
print(even)

#3. Convert a list of strings to uppercase.
li = ["apple", "banana", "mango"]
result=[i.upper()for i in li]
print(result)

#4. Filter numbers greater than 10 from a list.
li = [5, 12, 7, 20, 3, 15]
result=[i for i in li if i > 10]
print(result)

#5. Create a list of lengths of words.
li = ["apple", "banana", "mango"]
length=[len(word) for word in li]
print(length)

#6. Flatten a 2D list into a 1D list.
li = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
flatten=[item for element in li for item in element]
print(flatten)

#7. Extract vowels from a string.
s='pythonprogramming'
vowels=[ch for ch in s if ch in 'a e i o u']
print(vowels)

#8. Create a list of common elements from two lists.
A = [1, 2, 3, 4]
B = [3, 4, 5, 6]
common=[i for i in A if i in B ]
print(common)