# -*- coding: utf-8 -*-
"""2nd_pdf_if_else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuR0CbyznC1mrDWHFnCyLBeUvsuyjDEO
"""

marks=int(input("enter marks="))
if(marks >= 40):
  print("pass")
  print("congratulations, keep it up")
else:
  print("fail")
  print("dont worry, try again")

age=int(input("enter age="))
if(age >= 18):
  print("allow you for voting")
else:
  remaining = 18 - age
  print(remaining,"years left to became eligible")

num=int(input("enter number="))
if(num % 2 == 0):
  print(num,"is an even number because it is divisible by 2")
else:
  print(num,"is not even number because it is not divisible by 2")

amount=int(input("enter purchase amount="))
if(amount > 1000):
  print("customer receives a discount")
else:
  print("customer not receives a discount")

temp=float(input("enter temperature="))
if(temp > 30):
  print("hot weather")
else:
  print("pleasant weather")

sal=int(input("enter salary="))
if(sal > 50000):
  print("high income")
else:
  print("average income")

num=int(input("enter number="))
if(num > 0):
  print(num,"is a positive number because it is greater than 0")
elif(num == 0):
  print(num,"is a zero number because it is equal to 0")
else:
  print(num,"is a negative number because it is less than 0")

pswrd=int(input("enter passwordr="))
correct_password=1234
if(pswrd == correct_password):
  print("login succesfull")
else:
  print("incorrect password")

marks=int(input("enter marks="))
if(marks >= 90):
  print("excellent")
else:
  print("needs improvement")

age=int(input("enter age="))
if(age >= 13):
  print("entry is allowed")
else:
  print("entry is denied")

a=int(input("enter first number="))
b=int(input("enter second number"))
if(a > b):
  print(a,"is greater than",b)
elif(b > a):
  print(b,"is greater than",a)
else:
  print("both num are equal")

amount=int(input("enter order amount="))
if(amount > 500):
  print("free delivery allow")
else:
  print("delivery charges apply")

year=int(input("enter year="))
if((year%4==0 and year%100!=0) or year%400==0):
  print(year,"is leap year")
else:
  print(year,"is not leap year")

num=int(input("enter income="))
if(num > 30000):
  print("approves a loan")
else:
  print("not approves a loan")

num=int(input("enter number="))
if(num >= 10 and num <= 100):
  print(num,"lies between 10 and 100")
else:
  print(num," does not lies between 10 and 100")

age=int(input("enter age="))
if(age >= 18):
  print("students as adults")
else:
  print("students are minors")

num=int(input("enter number="))
if(num % 5 == 0):
  print(num,"is divisible by 5 beacuse it leaves remainder 0")
else:
  print(num,"is not divisible by 5")

attendance=float(input("enter attendance percentage="))
if(attendance >= 75):
  print("allow student to sit in exam")
else:
  print("deny permission")

num=int(input("enter number="))
if(num >= 100 and num <= 999) or (num >= -999 and num <= -100):
  print(num,"is a three digit number")
else:
  print(num,"is not a three digit number")

age=int(input("enter age="))
if(age >= 18 and age <= 60):
  print(age,"is eligible for gym membership")
else:
  print(age,"is not eligible for gym membership")

experience=int(input("enter experience="))
if(experience > 5):
  print("bonus is granted")
else:
  print("bonus is not granted")

num=int(input("enter number="))
if(num > 100):
  print(num,"is greater than 100")
else:
  print(num,"is not greater than 100")

height=float(input("enter height in cm="))
if(height > 170):
  print("tall ")
else:
  print("average height")

num=int(input("enter number="))
if(num % 2 == 0 and num % 3 == 0):
  print(num,"is divisible by both 2 and 3 because it is divisible by 6")
else:
  print(num,"is not divisible by 2 and 3")

fine=int(input("enter fine amount="))
if(fine == 0):
  print("issues the books")
else:
  print("book not be issued")

age=int(input("enter age="))
if(age >= 18):
  print("approve the application")
else:
  print("application is not approved because your age is below from 18")

marks=int(input("enter marks="))
if(marks > 60):
  print("above average performance")
else:
  print("average performance")

score=int(input("enter score="))
if(score > 70):
  print("access status granted")
else:
  print("access is not granted")

num=int(input("enter number="))
if(num < 50):
  print(num,"less than 50 because it is smaller than 50")
else:
  print(num,"not less than 50 because it is greater than or equal to 50")

amount=int(input("enter bill amount="))
if(amount > 2000):
  print("offer is applicable")
else:
  print("offer is not applicable")