# -*- coding: utf-8 -*-
"""3rd_pdf_nested_if.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j_WOM3ASx7wI2ArghkghW-NTzE7xtKR
"""

marks=int(input("enter marks="))
if(marks >= 40):
  if marks > 75:
    print("distinction")
  else:
    print("pass")
else:
  print("fail")

num=int(input("enter number="))
if(num > 0):
  if num % 2 == 0:
    print("positive even number")
  else:
    print("positive odd number")
else:
  print("negative number")

age=int(input("enter age="))
if(age >= 18):
  if age > 60:
    print("senior citizen")
  else:
    print("adult")
else:
  print("minor")

experience=float(input("enter experience="))
salary=int(input("enter salary"))
if(experience > 2):
  if salary < 30000:
    print("approve a salary hike")
  else:
    print("not approve salary hike")
else:
  print("not eligible, experience is leess than or equal to 2 years")

num=int(input("enter number="))
if(num % 2 == 0):
  if num % 4 == 0:
    print("divisible by both 2 and 4")
  else:
    print("only divisible by 2 ")
else:
  print("not divisible by 2")

marks=int(input("enter marks="))
if(marks >= 40):
  if marks > 90:
    print("award a scholarship")
  else:
    print("pass")
else:
  print("fail")

income=int(input("enter income="))
credit_score=int(input("enter credit score="))
if(income > 25000):
  if credit_score >= 700:
    print("loan approved")
  else:
    print("further verification required")
else:
  print("loan not approved")

correct_username = "admin"
correct_password = 1234

username = input("Enter username: ")
password = int(input("Enter password: "))

if (username == correct_username):
    if password == correct_password:
        print("Login Successful")
    else:
        print("Incorrect Password")
else:
    print("Incorrect Username")

temperature = float(input("Enter temperature: "))

if (temperature > 20):
    if temperature > 35:
        print("very hot")
    else:
      print("normal weather")
else:
  print("cold weather")

attendance= float(input("Enter attendance percentage="))
marks=int(input("enter marks="))
if (attendance > 75):
    if marks >=40 :
        print("eligible for exam")
    else:
      print("not eligible due to 3low marks")
else:
  print("deny exam permission")

num=int(input("enter number="))
if (num > 0):
    if num < 50 :
        print("it lies in the range of 1 to 49")
    else:
      print("Number is positive but not in the valid range")
else:
  print("number is not greater than 0")

amount = float(input("Enter purchase amount: "))
membership = input("Are you a member (yes/no): ")

if amount > 1000:
    if membership == "yes":
        print("Extra discount applied")
    else:
        print("No extra discount (not a member)")
else:
    print("amount less than or equal to 1000)")

year= int(input("enter year= "))
if (year % 4 == 0):
    if year % 100 == 0:
      if year % 400 == 0:
        print("leap year")
      else:
        print("not a leap year")
    else:
      print("leap year")
else:
  print("not a leap year")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a > b:
    if a > c:
        print(a,"is the largest")
    else:
        print(c,"is the largest")
else:
    if b > c:
        print(b,"is the largest")
    else:
        print(c,"is the largest")

correct_username = "student"
correct_password = 12345

username = input("Enter username: ")
password = int(input("Enter password: "))
payment = input("Is course payment completed? (yes/no): ")

if username == correct_username and password == correct_password:
    print("Login Successful")

    if payment == "yes":
        print("Access to course granted")
    else:
        print("Please complete payment to access the course")
else:
    print("Login Failed")

age = int(input("Enter age: "))
rating = input("Is the show 18+ (yes/no): ")

if (age > 13):
    if rating == "yes":
        if age >= 18:
            print("Entry Allowed")
        else:
            print("Entry Denied 18+ show")
    else:
        print("Entry Allowed")
else:
    print("Entry Denied Age below 13")

membership = input("Do you have membership (yes/no): ")
payment = input("Is payment done (yes/no): ")

if membership == "yes":
    if payment == "yes":
        print("Entry Allowed")
    else:
        print("Entry Denied")
else:
    print("No Membership")

location = input("Is location serviceable (yes/no): ")
amount = int(input("enter order amount: "))

if location == "yes":
    if amount >= 500:
        print("free Delivery Available")
    else:
        print("delivery charges applicable")
else:
    print("delivery is not available in your area")

num = int(input("enter number="))

if num > 0:
    if num % 5 == 0:
        print(num,"is positive and divisible by 5")
    else:
        print(num,"is positive but not divisible by 5")
else:
    print("number is not positive")

marks = int(input("enter marks= "))

if marks > 50:
    if marks > 85:

        print("Grade A")
    else:
        print("Grade B")
else:
    print("Fail")

qualification = input("Is qualification valid yes/no: ")
experience = float(input("Enter years of experience: "))

if qualification == "yes":
    if experience >= 2:
        print("Candidate shortlisted")
    else:
        print("Not shortlisted insufficient experience")
else:
    print("Not shortlisted invalid qualification")

student_id = input("Enter student ID: ")
fine = int(input("Enter fine amount: "))

if student_id == "valid":
    if fine == 0:
        print("Book issued successfully")
    else:
        print("Cannot issue book pending fine")
else:
    print("Invalid student ID")

reservation = input("Do you have a reservation (yes/no): ")
arrival_time = int(input("Enter arrival time: "))

if (reservation == "yes"):
    if (arrival_time >=10 and arrival_time <= 22):
        print("Seating Allowed")
    else:
        print("Reservation valid but outside service hours")
else:
    print("No reservation")