# -*- coding: utf-8 -*-
"""Class_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XePVryi1Rek5AiHbQTfMVsZev-wrcrTA
"""

#1. Differentiate between compiled and interpreted languages with at least two examples each.
# 1.Compiled Languages-
# Converted into machine code before running
# Faster execution
# Examples: C, C++

# 2.Interpreted Languages-
# Executed line by line
# Slower execution
# Examples: Python, JavaScript

# #2. Explain how conditional statements work in programming.
# Conditional statements are used to make decisions in a program.

# They check a condition (true or false) and run code based on the result.

# How it works:
# If the condition is true = code runs
# If the condition is false = code is skipped or another block runs

# #3. Write the syntax of a for loop and explain its components.
# syntax of for loop
# for variable in sequence:
#     # code to run
# Components:
# for - keyword to start the loop
# variable - takes value one by one from the sequence
# in - used to connect variable with sequence
# sequence - collection (like range,etc)
# body - code inside loop that runs repeatedly

# #4. What is a while loop? When should it be preferred over a for loop?
# A while loop repeats a block of code as long as a condition is true.
# while condition:
#     # code

# You don’t know the number of iterations in advance
# The loop depends on a condition not a fixed range

# #5. Write two key differences between for loop and while loop.
# for loop - 1.used when number of iterations is known
#            2.automatically handles iteration uses range or sequence

# while loop-1.used when number of iterations is not known
#            2.runs based on a condition needs manual update

#6.Write a program to check whether a number is positive, negative, or zero.
n=10
if n > 0:
    print("Positive")
elif n < 0:
    print("Negative")
else:
    print("Zero")

#7. Write a program to check if a person is eligible to vote (age ≥ 18).
age=20
if age>=18:
  print("eligible for vote")
else:
  print("not eligible for vote")

#8.Write a program to find the greatest of two numbers.
a=70
b=50
if a>b:
  print("a is greater")
elif b>a:
  print("b is greater")
else:
  print("both are equal")

#9.Write a program to check whether a number is even or odd.
n=12
if n % 2==0:
  print("even number")
else:
  print("not even number")

#10. Write a program to assign grades based on marks:
# 90+ → A
# 75–89 → B
# 50–74 → C
# Below 50 → Fail
marks=90
if marks >= 90:
    print("A")
elif marks >=75 and marks <=89:
    print("B")
elif marks >=50 and marks <=74:
    print("C")
else:
    print("Fail")

#11. Write a program to print numbers from 1 to 10 using a for loop.
for i in range(1,11):
  print(i)

#12. Write a program to print all even numbers from 1 to 50.
for i in range(1,51):
  if i % 2 == 0:
    print(i)

#13. Write a program to find the sum of first N natural numbers.
n=5
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

#14. Write a program to print the multiplication table of a given number.
n=2
for i in range(1,11):
  print(n,"*",i,"=",n*i)

#15. Write a program to count how many numbers between 1 and 100 are divisible by 5.
count=0
for i in range(1,101):
  if i % 5 == 0:
    count+=1
print(count)

#16. Write a program to print numbers from 10 to 1 using a while loop.
n=10
while n >= 1:
  print(n)
  n=n-1

#17. Write a program to find the sum of digits of a number using a while loop.
n=1234
sum=0
while n > 0:
  rem=n % 10
  sum=sum+rem
  n=n // 10
print(sum)

#18. Write a program to reverse a number using a while loop.
n=5426
rev=0
while n > 0:
  rem=n % 10
  rev=rev*10+rem
  n=n // 10
print(rev)

#19. Write a program to check whether a number is a palindrome using a while loop (without slicing).
n=121
temp=n
rev=0
while n > 0:
  rem=n % 10
  rev=rev*10+rem
  n=n // 10
if rev == temp:
  print("Palindrome Number")
else:
  print("Not palindrome Number")

#20. Write a program to keep taking input from the user until the user enters a negative number.
while True:
    num = int(input("Enter a number: "))
    if num < 0:
      print("Negative number,loop is stop")
      break
    print("You entered:", num)