# -*- coding: utf-8 -*-
"""Class_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZSw4EC9IMtFm3Mj6xR6-WZekeUe52bd
"""

n=231
largest=0
while n > 0:
  digit= n % 10
  if digit > largest:
    largest=digit
  n=n // 10
print(largest)

li=[1,2,3,4,5]
for i in range(len(li)-1,-1,-1):
  print(li[i])

li=[1,2,3,4,5]
sum=0
for i in range(len(li)):
  sum+=li[i]
print(sum)

li=[1,2,3,4,5]
prod=1
for i in range(len(li)):
  prod*=li[i]
print(prod)

li=[1,2,3,4,5]
for i in range(len(li)):
  if li[i] % 2 == 0:
    print(li[i])

li=[1,2,3,4,5]
for i in range(len(li)):
  if li[i] % 2 != 0:
    print(li[i])

li=[1,2,3,4,5]
larg=li[0]
for i in range(len(li)):
  if li[i] > larg:
    large = li[i]
print(large)

li=[4,5,2,1]
small=li[0]
for i in range(len(li)):
  if li[i] < small:
    small = li[i]
print(small)

li=[1,2,3,4,5,6,7,8,9,10]
even_li=[]
odd_li=[]

for i in range(len(li)):
  if i%2==0:
    even_li.append(i)
  else:
    odd_li.append(i)
print(even_li)
print(odd_li)

li = [1, 2, 3, 4, 5]
rev = li[::-1]
print(rev)

li = [1, 2, 3, 4, 5]
left=0
right=len(li)-1
while left < right:
  li[left],li[right]=li[right],li[left]
  left+=1
  right-=1
print(li)

li = [1, 2, 3, 4, 5]
k=2
print(li[-2:])
print(li[:-2])
print(li[-2:]+li[:-2])

li=[2,-3,1,-4,0]
li=[x if x > 0 else 0 for x in li]
print(li)

li=[[1,2,3],[4,5,6],[7,8,9]]

large=li[0][0]
for i in li:
  for j in i:
    if j > large:
      large=j
print(large)

li=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
large=li[0][0]
for i in li:
  for j in i:
    if j > large:
      large=j
print(large)

li=[[1,2,3],[4,5,6],[7,8,9]]
sum=0
for i in range(len(li)):
  for j in range(len(li)):
    if i==j:
      sum=sum+li[i][j]
print(sum)

t=(1,2)
type(t)

a=1,2,3
type(a)

keys = ['name', 'location', 'roll']
values = ['rahul', 'jaipur', 29]

mydict = {}
for i in range(len(keys)):
  print(f'{keys[i]}-{values[i]}')
  mydict[keys[i]]=values[i]
print(mydict)

d={'name': 'rahul', 'location': 'jaipur', 'roll': 29}
swapped={}
for key,value in d.items():
  swapped[value]=key
print(swapped)

d={'name': 'rahul', 'location': 'jaipur', 'roll': 29}
new={}
for key,value in d.items():
  new[key]=value
print(new)

d={'a':1,'b':3,'c':2}
largest=0
largest_key=''
for key,value in d.items():
  if value > largest:
    largest=value
    largest_key=key
print(largest_key)

char = 'aaabbcc'
freq = {}
for ele in char:
  if ele in freq:
    freq[ele] += 1
  else:
    freq[ele] = 1
print(freq)

st='this is a sentence this is a very best'.split()
freq={}
for word in st:
  if word in freq:
    freq[word]+=1
  else:
    freq[word]=1
print(freq)

li=[1,2,3,4,5,6,7]
d={'even':[],'odd':[]}
for i in li:
  if i%2==0:
    d['even'].append(i)
  else:
    d['odd'].append(i)
print(d)

words = ['apple', 'aeroplane', 'ball', 'banana','cat','cup']
result = {}

for w in words:
    first = len(w)
    if first in result:
        result[first].append(w)
    else:
        result[first] = [w]

print(result)