# -*- coding: utf-8 -*-
"""For_loop_40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvp4RvY0Vc3-dVnaNI85H9gO3ZQyRoBe
"""

#1. Print numbers from 1 to 50 using a for loop.
for i in range(1,51):
  print(i)

#2. Print numbers from 50 to 1 using a for loop.
for i in range(50,0,-1):
  print(i)

#3.Print all even numbers between 1 and 100.
for i in range(1,101):
  if i % 2==0:
    print(i)

#4. Print all odd numbers between 1 and 100.
for i in range(1,101):
  if i % 2 != 0:
    print(i)

#5. Print numbers from 10 to 100 with a step of 10.
for i in range(10,101,10):
    print(i)

#6. Print the square of numbers from 1 to 10.
for i in range(1,11):
    print(i*i)

#7. Print the cube of numbers from 1 to 5.
for i in range(1,6):
    print(i**3)

#8. Find the sum of numbers from 1 to 100 using a for loop.
sum=0
for i in range(1,101):
  sum=sum+i
  print(sum)

#9. Print the table of 9 using a for loop.
n=9
for i in range(1,11):
  print(n,"*",i,"=",n*i)

#10. Print numbers from 1 to 30 but skip multiples of 4.
for i in range(1,31):
  if i % 4 != 0:
    print(i)

#11. Print numbers from 1 to 50 and stop the loop when the number becomes 25 using
#break.
for i in range(1,51):
  if i == 25:
    break
  print(i)

#12. Print numbers from 1 to 100 and stop when you encounter the first number divisible by 7.
for i in range(1,101):
  if i % 7 == 0:
    break
  print(i)

#13. Print numbers from 1 to 40 but skip numbers divisible by 5 using continue.
for i in range(1,41):
  if i % 5 == 0:
    continue
  print(i)

#14. Print numbers from 10 to 1 and stop when the number becomes 4.
for i in range(10,0,-1):
  if i == 4:
        break
  print(i)

#15. Print all numbers from 1 to 100, but skip numbers between 30 and 40.
for i in range(1,101):
  if i >= 30 and i <= 40:
    continue
  print(i)

#16. Print numbers from 1 to 100 and stop when a number ends with 7.
for i in range(1,101):
  if i % 10 == 7:
    break
  print(i)

#17. Print numbers from 1 to 50, skip even numbers, and print only odd numbers.
for i in range(1,50):
  if i % 2 == 0:
    continue
  print(i)

#18. Print numbers from 1 to 100 and stop when you find a number divisible by both 3 and 5.
for i in range(1,101):
  if i % 3 == 0 and i % 5 ==0:
    break
  print(i)

#19. Print numbers from 1 to 60 but skip multiples of 6.
for i in range(1,61):
  if i % 6 == 0:
    continue
  print(i)

#20. Print numbers from 100 to 1 and stop when the number becomes 55.
for i in range(100,0,-1):
  if i == 55:
    break
  print(i)

#21. Print numbers from 1 to 30 but skip numbers between 10 and 20.
for i in range(1,31):
  if i >= 10 and i <= 20:
    continue
  print(i)

#22. Print numbers from 1 to 100 and stop when the sum crosses 200.
sum=0
for i in range(1,101):
  sum=sum+i
  if sum > 200:
      break
  print(i)

#23. Print numbers from 1 to 50 but skip numbers ending with 3.
for i in range(1,51):
  if i % 10 == 3:
    continue
  print(i)

#24. Print numbers from 1 to 100 and stop when you encounter the first even number greater
#than 50.
for i in range(1,101):
  if i % 2 == 0 and i > 50:
      break
  print(i)

#25. Print numbers from 1 to 40 and skip numbers divisible by both 2 and 3.
for i in range(1,41):
  if i % 2==0 and i % 3==0:
      continue
  print(i)

#26. Print numbers from 1 to 10 using a while loop.
i=1
while i<=10:
  print(i)
  i=i+1

#27. Print numbers from 20 to 1 using a while loop.
i=20
while i>=1:
  print(i)
  i=i-1

#28. Print all even numbers between 1 and 50 using a while loop.
i=1
while i <= 50:
  if i % 2 == 0:
    print(i)
  i=i+1

#29. Print all odd numbers between 1 and 50 using a while loop.
i=1
while i <= 50:
  if i % 2 != 0:
    print(i)
  i=i+1

#30. Print the table of 5 using a while loop.
n=5
i=1
while i <= 10:
  print(n,"*",i,"=",n*i)
  i=i+1

#31. Find the sum of numbers from 1 to 100 using a while loop.
i=1
sum=0
while i <= 100:
  sum=sum+i
  i=i+1
  print(sum)

#32. Print numbers from 10 to 100 with a step of 10 using a while loop.
i=10
while i <= 100:
  print(i)
  i=i+10

#33. Print the square of numbers from 1 to 10 using a while loop.
i=1
while i <= 10:
  print(i*i)
  i=i+1

#34. Count from 1 to 30 using a while loop.
i=1
count=0
while i <= 30:
  count=count+1
  print(count)
  i=i+1

#35. Print numbers from 100 to 0 with a step of -5 using a while loop.
i=100
while i >= 0:
  print(i)
  i=i-5

#36. Print all multiples of 7 between 1 and 100 using a while loop.
i=1
while i <= 100:
  if i % 7 ==0:
    print(i)
  i=i+1

#37. Find the product of numbers from 1 to 10 using a while loop.
i=1
product=1
while i <= 10:
  product=product*i
  i=i+1
print(product)

#38. Print numbers from 1 to 50 but skip multiples of 4 using a while loop.
i=1
while i <= 50:
  if i % 4 == 0:
    i=i+1
    continue
  print(i)
  i=i+1

#39. Print numbers from 1 to 100 and stop when the number becomes 60 using a while loop.
i=1
while i <= 100:
  if i == 60:
    break
  print(i)
  i=i+1

#40. Print numbers from 1 to 40 but stop when a number ends with 9 using a while loop.
i=1
while i <= 40:
  if i % 10 ==9:
    break
  print(i)
  i=i+1