# -*- coding: utf-8 -*-
"""Leetcode_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDNvJG2E47z-eviKF4rh9t9dj7kKNfWF
"""

def sum(num,target):
  for i in range(len(num)):
    for j in range(i+1,len(num)):
      if num[i]+num[j]==target:
        return [i,j]

num=[1,2,3,4,5]
target=7
print(sum(num,target))

def group_anagram(words):
  d={}
  for word in words:
    key=''.join(sorted(word))
    if key in d:
      d[key].append(word)
    else:
      d[key]=[word]
  return list(d.values ())

words= ["eat","tea","tan","ate","nat","bat"]
print(group_anagram(words))

# nums=[1,2,3,4]
def array(nums):
  li=[]
  for i in range(len(nums)):
    product=1
    for j in range(len(nums)):
      if i !=j:
        product=product*nums[j]
    li.append(product)
  return li

nums=[1,2,3,4]
print(array(nums))



