# -*- coding: utf-8 -*-
"""list_15_Questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PO7g0zAVTzgRLEGLtVXIHIPDia2D0jPq
"""

# 1. Average of elements
# Input: Enter number of elements: 5 Enter elements: 10 20 30 40 50
# Output: Average of elements is: 30.0
n= int(input("Enter number of elements: "))
sum=0
li=[]
for i in range(n):
  num = int(input("Enter elements: "))
  li.append(num)
for i in li:
  sum+=i
avg=sum/n
print(sum)
print(avg)

# 2. Count elements greater than a number
# Input: Enter number of elements: 5 Enter elements: 5 10 15 20 25 Enter a number: 12
# Output: Number of elements greater than 12 is: 3
n= int(input("Enter number of elements: "))
li=[]
for i in range(n):
  num= int(input("Enter elements: "))
  li.append(num)
element=int(input("Enter a number: "))
count=0
for i in li:
  if i > element:
    count+=1
print("number of elements greater than",element,"is",count)

# 3. Count even and odd elements
# Input: Enter number of elements: 6 Enter elements: 1 2 3 4 5 6
# Output: Even count: 3 Odd count: 3
n= int(input("Enter number of elements: "))
li=[]
for i in range(n):
  num= int(input("Enter elements: "))
  li.append(num)

even_count=0
odd_count=0
for i in li:
  if i % 2 == 0:
    even_count+=1
  else:
    odd_count+=1
print("Even count=",even_count)
print("Odd count=",odd_count)

# 4. Difference between max and min
# Input: Enter number of elements: 5 Enter elements: 10 5 25 2 18
# Output: Difference between max and min is: 23
n= int(input("Enter number of elements: "))
li=[]
for i in range(n):
  num= int(input("Enter elements: "))
  li.append(num)

max=li[0]
min=li[0]
for i in li:
  if i > max:
    max=i
  if i < min:
    min=i
difference=max-min
print("Difference between max and min=",difference)

# 5. Second largest element
# Input: Enter number of elements: 5 Enter elements: 10 20 4 45 99
# Output: Second largest element is: 45
li=[10,20,4,45,99]
first_largest=li[0]
second_largest=li[0]
for i in li:
  if i > first_largest:
    second_largest=first_largest
    first_largest=i
  elif i < first_largest and i > second_largest:
    second_largest=i
print("first largest=",first_largest)
print("second largest=",second_largest)

# 6. Second smallest element
# Input: Enter number of elements: 5 Enter elements: 8 3 5 1 9
# Output: Second smallest element is: 3
li=[8,3,5,1,9]
first_smallest=li[0]
second_smallest=li[0]
for i in li:
  if i < first_smallest:
    second_smallest=first_smallest
    first_smallest=i
  elif i > first_smallest and i < second_smallest:
    second_smallest=i
print("first smallest=",first_smallest)
print("second smallest=",second_smallest)

# 7. Count occurrence of an element
# Input: Enter number of elements: 6 Enter elements: 1 2 2 3 4 2 Enter element to count: 2
# Output: Element 2 appears 3 times
n= int(input("Enter number of elements: "))
li=[]
for i in range(n):
  num= int(input("Enter elements: "))
  li.append(num)
element=int(input("enter element to count="))
count=0
for i in li:
  if i == element:
    count+=1
print("Element 2 appears=",count,"times")

# 8. Check element exists or not
# Input: Enter number of elements: 5 Enter elements: 10 20 30 40 50 Enter element to search: 30
# Output: Element found in the list
n = int(input("Enter number of elements: "))
li = []

for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

element = int(input("enter element for search="))
found = False
for i in li:
    if i == element:
        found = True

if found:
    print("element found in the list")
else:
    print("not found in the list.")

# 9. Find index of an element
# Input: Enter number of elements: 5 Enter elements: 5 10 15 20 25 Enter element to find index: 15
# Output: Element found at index: 2
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

element = int(input("enter element to find index="))
index=-1
for i in range(len(li)):
  if li[i]==element:
    index = i
if index > -1:
  print("element found at index=",index)
else:
  print("element not found")

# 10. Count elements divisible by 5
# Input: Enter number of elements: 6 Enter elements: 5 10 12 15 18 20
# Output: Number of elements divisible by 5: 4
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

count=0
for i in li:
  if i % 5 == 0:
    count+=1
print("Number of elements divisible by 5=",count)

# 11. Squares of all elements
# Input: Enter number of elements: 4 Enter elements: 2 3 4 5
# Output: New list with squares: 4 9 16 25
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)
new_li=[]
for i in li:
  new_li.append(i**2)
print("New list with squares=",new_li)

# 12. List of even numbers
# Input: Enter number of elements: 6 Enter elements: 1 2 3 4 5 6
# Output: Even numbers list: 2 4 6
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

even_li=[]
for i in li:
  if i % 2 == 0:
    even_li.append(i)
print("Even numbers list=",even_li)

# 13. Replace negative numbers with 0
# Input: Enter number of elements: 5 Enter elements: -1 2 -3 4 5
# Output: Updated list: 0 2 0 4 5
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)
#update_li=[]
for i in range(len(li)):
  if li[i] < 0:
    li[i] = 0
print("updated list=",li)

# 14. Multiply each element by 2
# Input: Enter number of elements: 4 Enter elements: 1 2 3 4
# Output: Updated list: 2 4 6 8
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

update_li=[]
for i in li:
  update_li.append(i*2)
print("Updated list=",update_li)

# 15. Add 5 to each element
# Input: Enter number of elements: 4 Enter elements: 10 20 30 40
# Output: Updated list: 15 25 35 45
n = int(input("Enter number of elements: "))
li = []
for i in range(n):
    num = int(input("Enter elements: "))
    li.append(num)

update_li=[]
for i in li:
  update_li.append(i+5)
print("Updated list=",update_li)

#16. Print the largest word from the list. li = ['this','is','a','sentence']
li = ['this','is','a','sentence']
largest=li[0]
for i in li:
  if len(i) > len(largest):
    largest = i
print("largest word is=",largest)

#17. Reverse the original list
li = ['this', 'is', 'a', 'sentence']
rev = []
for i in range(len(li)-1, -1, -1):
    rev.append(li[i])

print("Reversed list=", rev)

#18. print the index of the two elements who sum is equal to target.
li=[1,2,3,4,5]
target=7
for i in range(len(li)):
  for j in range(i+1,len(li)):
    if li[i]+li[j]==target:
      print(i,j)
    break