# -*- coding: utf-8 -*-
"""Nested_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1q6CZQLsQ_t46tMVIXk39F2BNE-2aih
"""

for row in range(1,6):
  for col in range(1,6):
    print(row,end='')
  print()

for row in range(5,0,-1):
  for col in range(5,0,-1):
    print(col,end='')
  print()

temp=1
for row in range(3):
  for col in range(3):
    print(temp,end='')
    temp=temp+1
  print()

for row in range(5,0,-1):
  for col in range(5,0,-1):
    print(row,end='')
  print()

for row in range(3):
  for col in range(3):
    print(chr(65+col),end=' ')
  print()

for row in range(3):
  for col in range(3,0,-1):
    print(chr(65+col-1),end=' ')
  print()

for row in range(3,0,-1):
  for col in range(3):
    print(chr(65+row-1),end=' ')
  print()