# -*- coding: utf-8 -*-
"""Pattern_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11W93mdkaGefOaYhPZ_B5MbKbH31gt1Dz
"""

#1.
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
  print()

#2.
n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(j,end=' ')
  print()

#3.
n=4
temp=1
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(temp,end=' ')
      temp+=1
  print()

#4.
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i<=j:
      print('*',end=' ')
  print()

#5.
n=4
for i in range(n,0,-1):
  for j in range(1,n+1):
    if i>=j:
      print(chr(65+j-1),end=' ')
  print()

#6.
n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(i,end=' ')
  print()

#7.
n=4
for i in range(0,n):
  for j in range(0,n):
    if i>=j:
      print(chr(65+j),end=' ')
  print()

#8.
n=5
for i in range(n,0,-1):
  for j in range(1,n+1):
    if i>=j:
      print(j,end=' ')
  print()

#9.
n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i<=j:
      print(j,end=' ')
  print()

#10.
n=5
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

#11.
n=6
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i<=j:
      print(chr(65+j-1),end=' ')
    else:
      print(' ',end=' ')
  print()