# -*- coding: utf-8 -*-
"""Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsCYBpmlObRBqfblQLQlDHWOWLXpDaXU
"""

for i in range(1,5+1):
  for j in range(1,5+1):
    if i==j or i+j==5+1 :
      print(1,end=' ')
    else:
      print(0,end=' ')
  print()

for i in range(1,5+1):
  for j in range(1,5+1):
    if i==1 or j==1 or i==5 or j==5:
      print('1', end=' ')
    else:
      print('0', end=' ')
  print()

n=7
for i in range(1,n+1):
  for j in range(1,n+1):
    if i==(n+1)//2 or j==(n+1)//2 :
      print('1', end=' ')
    else:
      print('0', end=' ')
  print()

n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')

  print()

n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(j,end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(i):
      print(chr(65+j),end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(i):
    print(chr(65+j),end=' ')
  print()

n=4
temp=1
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(temp,end=' ')
      temp=temp+1
    else:
      print(' ',end=' ')

  print()

n=4
temp=1
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(i,end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
temp=1
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+temp-1),end=' ')
      temp+=1
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(n-i+1,end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(n-i+j,end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+i-j),end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+n-i),end=' ')
    else:
      print(' ',end=' ')

  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+n-j),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(n-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(n-i+j,end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+n-i),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+i-1),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65+i-j),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i>=j:
      print(chr(65 + n -1-(i-j)),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')
  for col in range(2*row-1):
    print('*',end=' ')
  print()

n=3
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(1,row+1):
    print(chr(65+col-1),end=' ')

  for col in range(row-1,0,-1):
    print(chr(65+col-1),end=' ')
  print()

n=4
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(1,row+1):
    print(chr(65+row-1),end=' ')

  for col in range(row-1,0,-1):
    print(chr(65+row-1),end=' ')
  print()

n=3
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(1,row+1):
    print(col,end=' ')

  for col in range(row-1,0,-1):
    print(col,end=' ')
  print()

n=3
temp=1
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(1,row+1):
    print(temp,end=' ')
    temp+=1

  for col in range(row-1,0,-1):
    print(temp,end=' ')
    temp+=1
  print()

n=4
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(n,0,-1):
    print(col,end=' ')
  print()

n=4
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(n,0,-1):
    print(chr(65+col-1),end=' ')
  print()

n=4
for row in range (1,n+1):
  for col in range (n-row):
    print(' ',end=' ')

  for col in range(n,0,-1):
    print(chr(65+n-col),end=' ')
  print()

n=4
for i in range (1,n+1):
  for j in range (n-i):
    print(' ',end='')

  for j in range(n,0,-1):
    if i==1 or j==1 or i==n or j==n:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i==1 or j==1 or i==n or j==n:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
      if j==i or i==n:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if i==n or j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
      if j==i or i==n:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if i==n or j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
      if j==i or i==n:
        print(i,end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if i==n or j==i:
        print(i,end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
      if j==i or i==n:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if i==n or j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(n,0,-1):
      if i==j or i==n or j==1:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
      if i==j or i==n or j==1:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(1,n+1):
      if i==n or i==j or j==1:
        print(chr(65+j-1),end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
      if j==i or i==n:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if i==n or j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  print()

# Diamond pattern-------
n=3
for i in range(1,n+1):
  for j in range(n,0,-1):
      if j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(n,0,-1):
      if j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if j==i:
        print('*',end=' ')
      else:
        print(' ',end=' ')
  print()

n=3
for i in range(1,n+1):
  for j in range(n,0,-1):
      if j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(n,0,-1):
      if j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  for j in range(2,n+1):
      if j==i:
        print(chr(65+i-1),end=' ')
      else:
        print(' ',end=' ')
  print()

n=4
for i in range(n,0,-1):
  for j in range(n,0,-1):
    if i==n or i==j:
      print("*", end=" ")
    else:
      print(" ",end=" ")
  for j in range(2,n+1):
    if i==n  or i==j:
      print("*", end=" ")
    else:
      print(" ",end=" ")

  print()
for i in range(2,n+1):
  for j in range(n,0,-1):
    if i==n or i==j:
      print("*", end=" ")
    else:
      print(" ",end=" ")
  for j in range(2,n+1):
    if i==n  or i==j:
      print("*", end=" ")
    else:
      print(" ",end=" ")
  print()

n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range(n-1,0,-1):
  for j in range(1,n+1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(j,end=' ')
    else:
      print(' ',end=' ')
  for j in range(n,0,-1):
    if i>=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range(1,n+1):
  for j in range(1,n+1):
    if i>=j:
      print(chr(65+j-1),end=' ')
    else:
      print(' ',end=' ')
  for j in range(n-1,0,-1):
    if i>=j:
      print(chr(65+j-1),end=' ')
    else:
      print(' ',end=' ')
  print()

n=4
for i in range (n,0,-1):
  for j in range (n,0,-1):
    if i >=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')

  for j in range (2,n+1):
    if i >=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range (2,n+1):
  for j in range (n,0,-1):
    if i >=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')

  for j in range (2,n+1):
    if i >=j:
      print(i-j+1,end=' ')
    else:
      print(' ',end=' ')
  print()

n=3
for i in range (n,0,-1):
  for j in range (n,0,-1):
    if i >=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')

  for j in range (2,n+1):
    if i >=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range (2,n+1):
  for j in range (n,0,-1):
    if i >=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')

  for j in range (2,n+1):
    if i >=j:
      print('*',end=' ')
    else:
      print(' ',end=' ')
  print()