# -*- coding: utf-8 -*-
"""PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1k-E0tAlBxya2bQSW7BTZwZ_dycgPGo
"""

n=10
count=0
for i in range(1,n+1):
  if n % i == 0:
    count=count+1
if count==2:
    print("prime number")
else:
    print("not prime number")

s = input("Enter string: ")

for i in range(len(s) - 1, -1, -1):
    print(s[i], end="")

s = "pineaaple"

vowels = "aeiou"
v_count = 0
c_count = 0

for ch in s:
    if ch in vowels:
        v_count += 1
    else:
        c_count += 1

print("Vowels:", v_count)
print("Consonants:", c_count)

s = "pythonprogramming"
vowels = "aeiou"

for i in range(len(s)):
    if i % 2 != 0 and s[i] not in vowels:
        print(s[i], end="")

s = "madam"  #check palindrome
rev=""
i = len(s) - 1

while i >= 0:
    rev=rev+s[i]
    i -= 1
if s==rev:
  print("palindrome")
else:
  print("not palindrome")

s1="listen"
s2="silent"
is_anagram=True
if len(s1)==len(s2):
  for c in s1:
    if c not in s2:
      is_anagram=False
      break
else:
  is_anagram=False
if is_anagram:
  print("anagram")
else:
  print("not anagram")

i=100
while i <=200:
  if i % 2 ==0:
    print(i)
  i=i+1

i=5
fact=1
while i >=1:
  fact=fact*i
  i=i-1
print(fact)

n=10
count=0
i=1
while i<=n:
  if n % i==0:
    count=count+1
  i=i+1
if count==2:
  print("prime")
else:
  print("not prime")

num=123
count=0
while num>0:
  num=num // 10
  count+=1
print(count)

n=123
count=0
sum=0
while n > 0:
  count=count+1
  n=n//10
  sum=sum+n
print()

n=200
i=100
while i <= n:
  if i % 3 == 0 and i % 8 == 0:
    print(i)
  i=i+1

