# -*- coding: utf-8 -*-
"""slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzDJI-UsDRS0_2_Lz9uAAXY6lVgfpTQ7
"""

s="pythonprogramming"
s[::-1]

s="pythonprogramming"
s[0:6][::-1]

s="pythonprogramming"
s[6:][::-1]

s="pythonprogramming"
s[-11:][::-2]

s="pythonprogramming"
s[-11:][-2::-3]

for i in range(100,0,-1):
  if(i % 5) == 0 and (i % 3) == 0 :
    print(i)

n=11
count=0
for i in range(1,n+1):
  if n % i==0:
    count+=1
if count==2:
  print("prime")
else:
  print("not prime")

n=2
is_prime=True
for i in range(2,n):
  if n % i==0:
    is_prime=False
if is_prime:
  print("prime")
else:
  print("not prime")