# -*- coding: utf-8 -*-
"""string_slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pP_gb5g4S0c_m-YVD79w9mQMkuxMTguT
"""

string = "Hello World"

first_char = string[0]

print("Full String:", string)
print("First Character:", first_char)

string = "Hello World"

last_char = string[-1:]

print("Full String:", string)
print("last Character:", last_char)

string = "Hello World"

first_char = string[0:2]

print("Full String:", string)
print("First 2 Character:", first_char)

string = "Hello Dushyant"

last_char = string[-3:]

print("Full String:", string)
print("last 3 Character:", last_char)

string = "Welcome"

char = string[1:]

print("Full String:", string)
print(" except first Character:", char)

string = "welcome"

char = string[:-1]

print("Full String:", string)
print("except last Character:",char)

string = "welcome dushyant"

char = string[1:-1]

print("Full String:", string)
print("except first and last Character:",char)

string = "dushyant"

char = string[2:6]

print("Full String:", string)
print("index 2 to 5 Character:",char)

string = "hello dushyant"

char = string[1:-1]

print("Full String:", string)
print("index 1 to second last position:",char)

string = "hello dushyant"

str = string[0:]

print("Full String=", string)
print("whole string=:",str)

string = "hello dushyant"

str = string[::-1]

print("Full String=", string)
print(" reverse whole string=:",str)

string = "hello"

first_four_char= string[0:4][::-1]

print("Full String=", string)
print(" reverse first 4 characters=:",first_four_char)

string = "hello world"

last_five_char= string[-5:][::-1]

print("Full String=", string)
print(" reverse last 5 characters=:",last_five_char)

string = "hello sharma"

char= string[1:][::-1]

print("Full String=", string)
print(" reverse string except first character=:",char)

string = "hello sharma"

char= string[:-1][::-1]

print("Full String=",string)
print(" reverse except last character=",char)

string = "python"

char= string[0] + string[1:-1][::-1] + string[-1]

print("Full String=", string)
print(" middle part of string=:",char)

string = "python"

mid= len(string) // 2
result=string[:mid][::-1] + string[mid:]

print("Full String=", string)
print(" first half of the string=:",result)

string = "python"

mid= len(string) // 2
result=string[:mid] + string[mid:][::-1]

print("Full String=", string)
print("second half of the string=:",result)

string = "python"

even=string[::2][::-1]

print("Full String=", string)
print("reverse character at even index position=:",even)

string = "python"

odd=string[1::2][::-1]

print("Full String=", string)
print("reverse character at odd index position=:",odd)

string = "python programming"

char=string[::2]

print("Full String=", string)
print("every second character=:",char)

string = "python programming"

char=string[::3]

print("Full String=", string)
print("every 3rd character=:",char)

string = "python"

char=string[::-2]

print("Full String=", string)
print("skip one character=:",char)

string = "python"

char=string[::-3]

print("Full String=", string)
print("skip  two character=:",char)

string = "python"

char=string[1::2]

print("Full String=", string)
print("alternate characters starting from index 1=",char)

string = "programming"

mid=len(string) // 2
result=string[mid-1:mid+2]
print("Full String=", string)
print("extract middle 3 characters=:",result)

string = "programming"

mid=len(string) // 2
result=string[mid-2:mid+3]
print("Full String=", string)
print("extract middle 5 characters=:",result)

string = "python"

mid=len(string) // 2
result=string[:mid]
print("Full String=", string)
print("extract first half string=:",result)

string = "python"

mid=len(string) // 2
result=string[mid:]
print("Full String=", string)
print("extract 2nd half string=:",result)

string = "python"

mid=len(string) // 2
result=string[:mid]
result_2=string[mid:]

print("Full String=", string)
print("first half=:",result)
print("second half=:",result_2)

string = "python"

n=2
result=string[n:] + string[:n]
print("full string=",string)
print("rotate string by left 2 position=:",result)

string = "python"

n=3
result=string[-n:] + string[:-n]
print("full string=",string)
print("rotate string right by 3 position=:",result)

string = "python"

result=string[-1] + string[1:-1] + string[0]
print("full string=",string)
print("swap first and last character=:",result)

string = "python"

result=string[-2:] + string[2:-2] + string[0:2]
print("full string=",string)
print("swap first two and last two character=:",result)

string = "python"

result=string[1:] + string[0]
print("full string=",string)
print("move first character to the end=:",result)

string = "python"

result=string[-1] + string[0:-1]
print("full string=",string)
print("move last character to the beginning=:",result)

string = "python"

result=string[2:]
print("full string=",string)
print("remove first 2 characters=:",result)

string = "python"

result=string[:-3]
print("full string=",string)
print("remove last 3 characters=:",result)

string = "python"

result=string[1:-2]
print("full string=",string)
print("remove first and last 2 characters=:",result)

string = "python"

mid=len(string) // 2
result=string[0:mid] + string[mid+1:]
print("full string=",string)
print("remove middle character of a string=",result)

string = "python"

result=string[0] + string[1:][::-1]
print("full string=",string)
print("string in reverse order but keep first character same=",result)

string = "python"

result=string[:-1][::-1] + string[-1]
print("full string=",string)
print("string in reverse order but keep last character same=",result)

string = "python"

result=string[::2][::-1]
print("full string=",string)
print("reverse only alternate character=",result)

string = "python"

result=string[::-1][0:4]
print("full string=",string)
print("reverse the string and print only first 4 character=",result)

string = "python"

result=string[::-1][0:-2]
print("full string=",string)
print("reverse the string and remove last 2 character=",result)

string = "python"

rev=string[::-1]
result=rev[1:] + rev[0]
print("full string=",string)
print("reverse the string and rotate left by 1 position=",result)

string = "python"
mid=len(string) // 2
result=string[:mid][::-1] + string[mid:]
print("full string=",string)
print("join the first half reverse & second half normal=",result)

string = "python"

mid=len(string) // 2
result=string[:mid] + string[mid:][::-1]
print("full string=",string)
print("join first half normal & second half reverse=",result)

s = "python"
print(s[::-1])  # nohtyp (reverse string)

s = "a b c"
print(s.split())   # ['a', 'b', 'c']

a = [1, 2, 3]
a.pop()
print(a)