# -*- coding: utf-8 -*-
"""While_loop_22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OhmCyswUQC4oEakSL5rw685QdnDk88t
"""

#1. Find the sum of first N natural numbers using a while loop.
n = int(input("Enter number: "))
i=1
sum=0
while i <= n:
  sum=sum+i
  i=i+1
print(sum)

#2. Find the factorial of a number using a while loop.
n = int(input("Enter number: "))
i=1
fact=1
while i <= n:
  fact=fact*i
  i=i+1
print(fact)

#3. Count the number of digits in a number using a while loop.
n = int(input("Enter number: "))
count=0
while n > 0:
  count+=1
  n=n // 10
print(count)

#4. Reverse a number using a while loop.
n = int(input("Enter number: "))
i=1
while n >= 1:
  print(n)
  n=n-1

#5. Check whether a number is a palindrome using a while loop.
n = int(input("Enter number: "))
rev=0
temp=n
while n > 0:
  digit=n % 10
  rev=rev*10+digit
  n = n // 10
if rev == temp:
  print("palindrome")
else:
  print("not palindrome")

#6. Find the sum of digits of a number using a while loop.
n = int(input("Enter number: "))
sum=0
while n > 0:
  digit=n % 10
  sum=sum+digit
  n = n // 10
print(sum)

#7. Find the product of digits of a number using a while loop.
n = int(input("Enter number: "))
product=1
while n > 0:
  digit=n % 10
  product=product*digit
  n = n // 10
print(product)

#8. Check whether a number is an Armstrong number using a while loop.
n = int(input("Enter number: "))
temp=n
temp1=n
count=0
while temp > 0:
  count+=1
  temp = temp // 10
sum=0
while temp1 > 0:
  digit=temp1 % 10
  sum=sum + digit ** count
  temp1=temp1 // 10
if sum==n:
  print("Armstrong number")
else:
  print("Not Armstrong number")

#9. Find the largest digit in a number using a while loop.
n = int(input("Enter number: "))
largest=0
while n > 0:
  digit=n % 10
  if digit > largest:
    largest=digit
  n = n // 10
print(largest)

#10. Find the smallest digit in a number using a while loop.
n = int(input("Enter number: "))
smallest=9
while n > 0:
  digit=n % 10
  if digit < smallest:
    smallest=digit
  n = n // 10
print(smallest)

#11. Keep taking numbers from the user and find their sum, but stop when the sum exceeds 100.
n = int(input("Enter number: "))
sum=0
i=1
while i <= n:
  sum=sum+i
  if sum > 100:
    break
  i=i+1
print("break at=",sum)

#12. Keep taking numbers and stop when a negative number is entered, then print the total sum.
total=0
while True:
  n=int(input("enter number="))
  if n < 0:
    break
  total=total+n
print(total)

#13. Find the first number divisible by both 3 and 5 in a given range, then break the loop.
n = int(input("Enter number: "))
i=1
while i <= n:
  if i % 3 ==0 and i % 5 ==0:
    print(i)
    break
  i=i+1

#14. Take numbers from user and stop when a palindrome number is entered.
while True:
  n = int(input("Enter number="))
  original=n
  rev=0
  while n > 0:
    digit=n % 10
    rev=rev*10+digit
    n=n//10
  if original == rev:
    print("palindrome number is entered stopped it")
    break
  else:
    print("not a palindrome number try again")

#15. Keep taking numbers and break when a number has more than 5 digits.
n = int(input("Enter number: "))
count=0
while n > 0:
  count+=1
  n = n // 10
  if count > 5:
    print("Number has more than 5 digits")
    break

#16. Print numbers from 1 to 100, skipping numbers whose digit sum is divisible by 5.
i=1
while i <= 100:
  n=i
  digit_sum=0

  while n > 0:
    rem=n % 10
    digit_sum+=rem
    n=n // 10
  if digit_sum % 5==0:
    i=i+1
    continue
  print(i)
  i=i+1

#17. Print numbers from 1 to 50, skipping numbers that are Armstrong numbers.
i = 1

while i <= 50:
    temp = i
    count = 0
    while temp > 0:
        count += 1
        temp = temp // 10

    temp2 = i
    sum = 0
    while temp2 > 0:
        rem = temp2 % 10
        sum = sum + rem ** count
        temp2 = temp2 // 10

    if sum == i:
        i = i + 1
        continue

    print(i)
    i = i + 1

#18. Print numbers from 1 to 100, skipping numbers that contain digit 0.
i = 1

while i <= 100:
    n = i

    while n > 0:
        if n % 10 == 0:
            break
        n = n // 10

    if n == 0:
        print(i)

    i = i + 1

#19. Print numbers from 1 to 100, skipping numbers whose reverse is same as original.
i=1
while i <= 100:
  n=i
  rev=0
  while n > 0:
    rem=n % 10
    rev=rev*10+rem
    n=n // 10
  if rev == i:
    i=i+1
    continue
  print(i)
  i=i+1

#20. Print numbers from 1 to 100, skipping numbers with even digit sum.
i=1
while i <= 100:
  n=i
  sum=0
  while n > 0:
    rem=n % 10
    sum=sum+rem
    n=n // 10
  if sum % 2 == 0:
    i=i+1
    continue
  print(i)
  i=i+1

#21. Take numbers from user, skip numbers whose digit sum is less than 10, and stop when
#sum exceeds 200.
total=0
while True:
  n=int(input("Enter number: "))
  digit_sum=0
  i=n
  while i > 0:
    rem=i % 10
    digit_sum=digit_sum+rem
    i= i // 10
  if digit_sum < 10:
    continue

  total=total + n
  if total > 200:
    print("total sum exceeds 200")
    break
print(total)

#22.Print numbers from 1 to 100, skip numbers divisible by 4, and break when a number
#divisible by 9 is found.
i=1
while i <= 100:
  if i % 4 == 0:
    i=i+1
    continue
  if i % 9 == 0:
    break
  print(i)
  i=i+1